version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - docker build -t laravel-coverage .
  post_build:
    on-failure: ABORT
    commands:
      - docker run --rm --volume $PWD/coverage:/var/www/html/coverage
        laravel-coverage php artisan test --coverage --coverage-xml coverage-clover/coverage.xml
reports:
  laravel-coverage:
    files:
      - coverage.xml
    base-directory: coverage-clover
    file-format: CLOVERXML
