version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - docker build -t laravel-coverage .
  post_build:
    on-failure: ABORT
    commands:
      - docker run --rm --volume $PWD/coverage-clover:/var/www/html/coverage-clover
        laravel-coverage ash -c "php artisan key:generate && php artisan test --coverage --coverage-xml coverage-clover/coverage.xml"
reports:
  laravel-coverage:
    files:
      - coverage-clover/coverage.xml
    file-format: CLOVERXML
    discard-paths: yes
