version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - docker build -t laravel-coverage .
  post_build:
    on-failure: ABORT
    commands:
      - docker run --rm --volume $PWD/coverage:/var/www/html/coverage
        laravel-coverage ash -c "php artisan key:generate && php artisan test --coverage-clover coverage/coverage.xml"
reports:
  laravel-coverage:
    files:
      - coverage/coverage.xml
    file-format: CLOVERXML
